# Generated by Django 2.2.1 on 2020-05-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('value', models.CharField(max_length=20)),
                ('expiry_date', models.DateTimeField()),
                ('revised', models.BooleanField()),
                ('contra_bet', models.ManyToManyField(related_name='_bet_contra_bet_+', to='odds.Bet')),
            ],
        ),
        migrations.CreateModel(
            name='BetMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('api_pass', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('player1', models.CharField(max_length=255)),
                ('player2', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('betable', models.BooleanField()),
                ('bets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odds.Bet')),
            ],
        ),
        migrations.CreateModel(
            name='ImportResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_start', models.DateTimeField()),
                ('date_finish', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odds.BetMarket')),
            ],
        ),
        migrations.CreateModel(
            name='SureBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=20)),
                ('benefit', models.CharField(max_length=20)),
                ('revised', models.BooleanField()),
                ('type', models.ManyToManyField(to='odds.Bet')),
            ],
        ),
        migrations.DeleteModel(
            name='BetModel',
        ),
        migrations.AddField(
            model_name='bet',
            name='market',
            field=models.ManyToManyField(to='odds.BetMarket'),
        ),
        migrations.AddField(
            model_name='bet',
            name='type',
            field=models.ManyToManyField(to='odds.BetType'),
        ),
    ]
