# Generated by Django 2.2.1 on 2020-05-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0002_auto_20200515_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surebet',
            old_name='type',
            new_name='bets',
        ),
    ]
