# Generated by Django 2.2.1 on 2020-05-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0004_auto_20200517_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='betmarket',
            name='alias',
            field=models.TextField(default=''),
        ),
    ]
