# Generated by Django 2.2.1 on 2020-05-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0005_betmarket_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettype',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
