# Generated by Django 2.2.1 on 2020-05-24 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0006_bettype_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='uuid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
