# Generated by Django 2.2.1 on 2020-05-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0008_auto_20200524_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surebet',
            name='benefit',
            field=models.FloatField(blank=True, max_length=20),
        ),
    ]
