# Generated by Django 2.2.1 on 2020-05-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0009_auto_20200524_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='revised',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surebet',
            name='events',
            field=models.ManyToManyField(blank=True, to='odds.Event'),
        ),
    ]
