# Generated by Django 2.2.1 on 2020-07-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0012_apiimporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='surebet',
            name='combined_bets_first',
            field=models.ManyToManyField(blank=True, related_name='firs_combined', to='odds.Bet'),
        ),
        migrations.AddField(
            model_name='surebet',
            name='combined_bets_second',
            field=models.ManyToManyField(blank=True, related_name='second_combined', to='odds.Bet'),
        ),
        migrations.AddField(
            model_name='surebet',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
